version: '3.5'
services:
  mysql:
    image: mariadb
    container_name: tf-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rojo1rojo2
      - MYSQL_DATABASE=TheForgotten
    restart: always
    ports:
      - '3306:3306'
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tf-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - '80:80'
    environment:
      - WORDPRESS_DB_NAME=TheForgotten
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=rojo1rojo2
    depends_on:
      - mysql
    restart: always

  composer:
    image: composer:latest
    container_name: tf-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
